#!/usr/bin/env bash

blue_='\033[0;34m'
green='\033[0;32m'
clear='\033[0m'

set -e

echo -e "\n${blue_}----> migrate the database${clear}"
rake db:migrate

echo -e "\n${blue_}----> run the tests${clear}"
rake

echo -e "\n${green}----> done${clear}"
