#!/usr/bin/env bash

set -e

yellow='\033[0;33m'
green='\033[0;32m'
clear='\033[0m'

function announce() {
  color="$1"
  msg="$2"
  echo -e "\n${color}----> ${msg}${clear}"
}

function step() {
  color="$1"
  msg="$2"
  echo -e "\n${color}      ${msg}${clear}"
}

function cleanup {
  announce "${yellow}" "Cleaning up"
  rm -rf ~/.gem
}

trap cleanup EXIT

announce "${yellow}" "Create the postgres databases"
psql -c 'CREATE DATABASE lalala_test' -U postgres

announce "${yellow}" "Run the tests"
rake

# Are we allowed to push gems?
if [[ "$TRAVIS_SECURE_ENV_VARS" == "true" && "$TRAVIS_PULL_REQUEST" == "false" ]]
then

  # Are we in the canonical environment?
  if [[ "$TRAVIS_BRANCH" == "master" && "$DB" == "postgresql" ]]
  then

    announce "${yellow}" "Push development gems"

    export LALALA_BUILD_VERSION="$TRAVIS_BUILD_NUMBER"

    mkdir -p "~/.gem/"
    echo -e "---\n:rubygems_api_key: ${RUBYGEMS_API_KEY}" > "~/.gem/credentials"

    { # set the build version
      cd lib/lalala
      mv version.rb version.rb_
      cat version.rb_ | sed "s|{{BUILD_NUMBER}}|$LALALA_BUILD_VERSION|" > version.rb
      rm version.rb_
      cd -
    }

    step "${yellow}" "Building lalala"
    rake lalala:build

    step "${yellow}" "Building lalala-assets"
    rake lalala-assets:build

    step "${yellow}" "Building lalala-development"
    rake lalala-development:build

    step "${yellow}" "Building lalala-test"
    rake lalala-test:build

  fi

fi

announce "${green}" "Done"
